# Generated by Django 4.0.2 on 2022-03-31 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='modo_prepraro',
            new_name='modo_preparo',
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 21, 53, 43, 781104)),
        ),
    ]
