# Generated by Django 4.0.2 on 2022-04-01 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_modo_prepraro_receita_modo_preparo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 31, 21, 3, 2, 272621)),
        ),
    ]
